# Generated by Django 3.0.6 on 2020-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isd_document',
            name='pdf',
            field=models.FileField(upload_to='ISD/'),
        ),
    ]
