# Generated by Django 3.0.6 on 2020-05-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200513_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='isd_document',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
