# Generated by Django 3.0.6 on 2020-05-25 16:31

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200519_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MIS_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('ISD', 'Information System Development'), ('EAM', 'Enterprise Architecture Management'), ('MIS', 'Management Information Systems'), ('BPM', 'Business Process Management'), ('DAS', 'Data and Application Security'), ('DM', 'Data Management'), ('BS', 'Business Statistics'), ('IL', 'Innovation Lab'), ('ISM', 'Information Systems Modelling'), ('DI', 'Digital Innovation'), ('DS', 'Data Science'), ('DB', 'Digital Business'), ('EIT', 'Emerging IT Topics'), ('HCD', 'Human Centered Design'), ('RM', 'Research Methods')], default='ISD', max_length=3)),
                ('pdf', models.FileField(upload_to=documents.models.MIS_Document.location)),
            ],
        ),
        migrations.DeleteModel(
            name='ISD_Document',
        ),
    ]
