# Generated by Django 3.0.6 on 2020-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200525_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mis_document',
            name='course',
            field=models.CharField(choices=[('ISD', 'Information System Development'), ('EAM', 'Enterprise Architecture Management'), ('MIS', 'Management Information Systems'), ('BPM', 'Business Process Management'), ('DAS', 'Data and Application Security'), ('DM', 'Data Management'), ('BS', 'Business Statistics'), ('IL', 'Innovation Lab'), ('ISM', 'Information Systems Modelling'), ('DI', 'Digital Innovation'), ('DS', 'Data Science'), ('DB', 'Digital Business'), ('EIT', 'Emerging IT Topics'), ('HCD', 'Human Centered Design'), ('RM', 'Research Methods'), ('RS', 'Research Seminar'), ('PS', 'Project Seminar'), ('MT', 'Master Thesis')], default='ISD', max_length=3),
        ),
    ]
